name: Commit
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types: [synchronize, opened, edited, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: npx hardhat compile
      - run: npx hardhat test
